type Facing = 'left' | 'right' | 'front';

const sourceFacing: Record<string, Facing> = {
  nerithe: 'left', 'nerithe-evo-2': 'left', 'nerithe-evo-3': 'left',
  'nerithe-evo-4': 'left', 'nerithe-evo-5': 'left', 'nerithe-evo-6': 'left',
  orvella: 'left', 'orvella-evo-2': 'left', 'orvella-evo-3': 'left',
  'orvella-evo-4': 'left', 'orvella-evo-5': 'left', 'orvella-evo-6': 'left',
  vaelor: 'left', 'vaelor-evo-2': 'left', 'vaelor-evo-3': 'left',
  'vaelor-evo-4': 'left', 'vaelor-evo-5': 'left', 'vaelor-evo-6': 'left',
  'fractured-watcher': 'left', 'ashwing-harrier': 'right', 'ivory-kirin': 'left',
  'celestial-leviathan': 'right', 'crowned-phoenix': 'front', 'ouroboros-first-dawn': 'left',
  atmoso: 'front', 'atmoso-evo-2': 'right', 'atmoso-evo-3': 'right',
  'atmoso-evo-4': 'left', 'atmoso-evo-5': 'front', 'atmoso-evo-6': 'left',
  aurora: 'left', 'aurora-evo-2': 'front', 'aurora-evo-3': 'front',
  'aurora-evo-4': 'front', 'aurora-evo-5': 'right', 'aurora-evo-6': 'front',
  bliss: 'front', 'bliss-evo-2': 'front', 'bliss-evo-3': 'front',
  'bliss-evo-4': 'front', 'bliss-evo-5': 'left', 'bliss-evo-6': 'front',
  bruno: 'left', 'bruno-evo-2': 'left', 'bruno-evo-3': 'left',
  'bruno-evo-4': 'right', 'bruno-evo-5': 'left', 'bruno-evo-6': 'left',
  disciple: 'left', 'disciple-evo-2': 'left', 'disciple-evo-3': 'front',
  'disciple-evo-4': 'front', 'disciple-evo-5': 'front', 'disciple-evo-6': 'front',
  elise: 'front', 'elise-evo-2': 'front', 'elise-evo-3': 'front',
  'elise-evo-4': 'front', 'elise-evo-5': 'front', 'elise-evo-6': 'front',
  razor: 'left', 'razor-evo-2': 'right', 'razor-evo-3': 'left',
  'razor-evo-4': 'right', 'razor-evo-5': 'front', 'razor-evo-6': 'front',
  rosetta: 'right', 'rosetta-evo-2': 'left', 'rosetta-evo-3': 'right',
  'rosetta-evo-4': 'right', 'rosetta-evo-5': 'right', 'rosetta-evo-6': 'right',
  thornia: 'left', 'thornia-evo-2': 'right', 'thornia-evo-3': 'left',
  'thornia-evo-4': 'left', 'thornia-evo-5': 'front', 'thornia-evo-6': 'left',
  crinso: 'left', 'crinso-evo-2': 'left', 'crinso-evo-3': 'left',
  'crinso-evo-4': 'left', 'crinso-evo-5': 'left', 'crinso-evo-6': 'left',
  roselius: 'right', 'roselius-golden-thorns': 'front', 'roselius-crimson-bloom': 'front',
  'roselius-seraph-passion': 'front', 'roselius-living-rose': 'front', 'roselius-garden-eternity': 'front',
  duskmote: 'right', 'veilcap-imp': 'left', 'gloomtail-cat': 'right',
  'hollowmantle-sentinel': 'left', 'umbrasilk-weaver': 'front', 'moonless-gargoyle': 'left',
  'eclipse-antler-regent': 'left', 'monarch-of-the-silent-eclipse': 'front',
  puffling: 'left', 'reedcap-sylph': 'right', 'gustfeather-harpy': 'left',
  'cloudhorn-ibex': 'left', 'zephyrcoil-drake': 'left', 'cyclonewing-griffin': 'left',
  'crownwind-roc': 'front', 'regent-of-the-unbroken-sky': 'left',
  riftpip: 'right', 'shardcap-gremlin': 'left', 'nullshell-scarab': 'left',
  'paradox-sentinel': 'left', 'fracturecoil-drake': 'left', 'riftwing-chimera': 'left',
  'crownvoid-behemoth': 'front', 'sovereign-of-the-impossible-ruin': 'front',
  pebblekin: 'left', 'claycap-kobold': 'right', 'flintback-armadillo': 'left',
  'quartzhorn-ram': 'left', 'geode-cyclops': 'left', 'pillarwing-gargoyle': 'left',
  'crownfault-behemoth': 'front', 'atlas-of-the-crystal-summit': 'front',
  glimmerkin: 'right', 'lanterncap-brownie': 'right', 'prismback-tortoise': 'right',
  'dawncrest-guardian': 'left', 'opalwing-griffin': 'left', 'sunmirror-oracle': 'left',
  'crownray-kirin': 'left', 'sovereign-of-the-sevenfold-dawn': 'right',
  infernis: 'left', 'infernis-evo-2': 'right', 'infernis-evo-3': 'right',
  'infernis-evo-4': 'left', 'infernis-evo-5': 'left', 'infernis-evo-6': 'left',
  tizu: 'right', 'tizu-evo-2': 'left', 'tizu-evo-3': 'right',
  'tizu-evo-4': 'left', 'tizu-evo-5': 'front', 'tizu-evo-6': 'left',
  flora: 'right', 'flora-evo-2': 'left', 'flora-evo-3': 'left',
  'flora-evo-4': 'left', 'flora-evo-5': 'right', 'flora-evo-6': 'right',
  goblin: 'left', imp: 'right', 'rock-golem': 'left',
  ashling: 'right', 'coalcap-kobold': 'left', 'emberhorn-faun': 'right',
  'furnace-salamander': 'left', 'cinderhide-cyclops': 'left', 'obsidian-gargoyle': 'left',
  'brasshorn-minotaur': 'right', 'pyrewing-harpy': 'left', 'magma-wyrm-knight': 'front',
  'last-furnace-ifrit': 'front',
  'pebblefin-sprig': 'left', 'shellcap-kappa': 'right', 'brineclaw-sentinel': 'left',
  'coralcrest-nereid': 'left', 'glasswake-kelpie': 'left', 'abyssbell-oracle': 'front',
  'pearlscale-leviathan': 'left', 'sovereign-of-the-endless-tide': 'front',
  budling: 'right', 'mosscap-brownie': 'front', 'thornshell-beetle': 'left',
  'petalhorn-satyr': 'left', 'orchid-mantis': 'left', 'moonbloom-dryad': 'front',
  'verdant-antler-regent': 'left', 'empress-of-the-thousand-blooms': 'front',
  hushbud: 'right', 'bellcap-keeper': 'front', 'lotusback-tortoise': 'left',
  'porcelain-crane': 'front', 'concord-lion': 'left', 'stillbell-oracle': 'front',
  'harmonywing-kirin': 'front', 'sovereign-of-the-unbroken-accord': 'front',
  sparkpip: 'right', 'coppercap-gremlin': 'left', 'coilback-scarab': 'front',
  'stormhorn-faun': 'left', 'thunderclaw-raiju': 'left', 'tempestwing-roc': 'left',
  'crowncoil-kirin': 'left', 'sovereign-of-the-living-storm': 'front',
  'heavens-dawnthorn-slime': 'right', 'heavens-scarlet-benediction': 'front',
  'heavens-gilded-reproach': 'front', 'heavens-thorns-first-light': 'left',
  'heavens-crimson-reckoning': 'left', 'heavens-dawn-without-mercy': 'right',
  'abyss-wraththorn-slime': 'front', 'abyss-starless-murmur': 'front',
  'abyss-ruins-awakening': 'left', 'abyss-hunger-beyond-veil': 'left',
  'abyss-worldfall-reverie': 'left', 'abyss-night-without-end': 'left',
  'gleamstone-slime': 'right', 'diadem-of-daybreak-gleamstone-slime': 'right',
  'scepter-of-radiance-gleamstone-slime': 'right', 'regalia-of-the-sun-gleamstone-slime': 'right',
  'sovereign-of-the-gilded-vault-gleamstone-slime': 'right', 'the-crown-beyond-dawn-gleamstone-slime': 'right',
  'rosethorn-wisp': 'right', 'votive-of-first-bloom-rosethorn-wisp': 'right',
  'laurel-of-the-sacred-flame-rosethorn-wisp': 'right', 'seraph-of-the-rose-pyre-rosethorn-wisp': 'right',
  'sovereign-of-the-hallowed-garden-rosethorn-wisp': 'right', 'the-flame-beyond-eternity-rosethorn-wisp': 'right',
};

export function unitFacing(art: string, side: 'ally' | 'enemy'): { facing: 'left' | 'right'; mirrored: boolean } {
  const source = sourceFacing[art];
  if (!source) throw new Error(`Unit facing metadata is missing: ${art}.`);
  const facing = side === 'ally' ? 'left' : 'right';
  return { facing, mirrored: source !== 'front' && source !== facing };
}

export function unitFacingAttributes(art: string, side: 'ally' | 'enemy'): string {
  const { facing, mirrored } = unitFacing(art, side);
  return `data-facing="${facing}" data-mirrored="${mirrored}"`;
}
