// Generated by tools/ability_art_revisions.py; regenerate after icon exports.
export const abilityArtRevisions: Readonly<Record<string, string>> = {
  'universal-defense': 'b68caa3cf0d17b72',
  'universal-normal-attack': 'ee16ec5ccb716e69',
};
