import type { ElementId } from './activities';
import type { ConduitBuff } from './conduits';
import type { ConduitKitEffects } from './conduit-kit';

interface KitConduitDesign {
  id: string;
  name: string;
  rarity: 'Common' | 'Rare' | 'Legendary' | 'Omnic';
  price: number | null;
  theme: ElementId;
  element: ElementId | null;
  buffs: readonly ConduitBuff[];
  effect: string;
  lore: string;
  kitEffects: ConduitKitEffects;
  artDesign: string;
}

export const kitConduitDesigns = [
  { id: 'tempered-strike-link', name: 'Tempered Strike Link', rarity: 'Common', price: 1500, theme: 'infernic', element: null,
    buffs: [{ stat: 'damage', kind: 'percent', amount: 3 }], kitEffects: { damage: [{ actions: ['light'], bonus: .05 }] },
    effect: '+3% Attack. Normal Attack deals +5% outgoing damage.',
    lore: 'A bronze striking link meters a short, deliberate pulse through a red ceramic pivot.',
    artDesign: 'small bronze hinged striking link with a crimson ceramic pivot and three short orange impact vanes' },
  { id: 'mending-valve', name: 'Mending Valve', rarity: 'Common', price: 1400, theme: 'botanic', element: null,
    buffs: [{ stat: 'health', kind: 'percent', amount: 3 }], kitEffects: { healing: .05 },
    effect: '+3% Health. Authored active and passive healing is 5% stronger; no healing is added to kits without it.',
    lore: 'A green ceramic valve opens around a protected ancient restoration channel.',
    artDesign: 'small bronze flower-shaped valve with jade ceramic shutters around a protected ivory restoration channel' },
  { id: 'ward-stitch-spool', name: 'Ward Stitch Spool', rarity: 'Common', price: 1400, theme: 'oceanic', element: null,
    buffs: [{ stat: 'defense', kind: 'percent', amount: 3 }], kitEffects: { shield: .05 },
    effect: '+3% Defense. Authored skill shields are 5% stronger; existing shields refresh rather than add.',
    lore: 'A blue-inlaid bronze spool keeps a measured ward ribbon between paired ceramic guides.',
    artDesign: 'small bronze spool with blue enamel inset and one opaque sapphire ward ribbon between ivory ceramic guides' },
  { id: 'cinder-metering-nozzle', name: 'Cinder Metering Nozzle', rarity: 'Common', price: 1600, theme: 'infernic', element: null,
    buffs: [{ stat: 'elementalDamage', kind: 'percent', amount: 3 }], kitEffects: { burn: .05 },
    effect: '+3% Elemental Damage. Authored Burn ticks are 5% stronger; duration and source stay unchanged.',
    lore: 'Three crimson baffles measure the pressure of an ancient ember channel.',
    artDesign: 'small bronze triangular nozzle with three crimson baffles and opaque orange pressure fins' },
  { id: 'pulse-trigger-pawl', name: 'Pulse Trigger Pawl', rarity: 'Common', price: 1800, theme: 'atmospheric', element: null,
    buffs: [{ stat: 'shatterCapacity', kind: 'flat', amount: 3 }], kitEffects: { normalGauge: 1 },
    effect: '+3 Shatter Capacity. Each legal Normal Attack gains 1 additional Gauge, capped by capacity.',
    lore: 'A teal ceramic tooth catches one extra pulse at the end of each ordinary strike.',
    artDesign: 'small bronze ratchet pawl with a teal ceramic tooth and one short opaque wind-shaped pulse band' },
  { id: 'firstlight-cam', name: 'Firstlight Cam', rarity: 'Rare', price: null, theme: 'tranquilitic', element: null,
    buffs: [{ stat: 'damage', kind: 'percent', amount: 15 }, { stat: 'health', kind: 'percent', amount: 12 }],
    kitEffects: { damage: [{ actions: ['skill1'], bonus: .08 }] }, effect: '+15% Attack ~ +12% Health. Damaging Skill 1 deals +8% outgoing damage.',
    lore: 'An ivory-inlaid cam directs a precise opening strike through silver articulated arms.',
    artDesign: 'silver asymmetrical cam with ivory petal inlays and two precision opening-strike arms' },
  { id: 'secondbeat-rack', name: 'Secondbeat Rack', rarity: 'Rare', price: null, theme: 'chaotic', element: null,
    buffs: [{ stat: 'damage', kind: 'percent', amount: 15 }, { stat: 'defense', kind: 'percent', amount: 12 }],
    kitEffects: { damage: [{ actions: ['skill2'], bonus: .08 }] }, effect: '+15% Attack ~ +12% Defense. Damaging Skill 2 deals +8% outgoing damage.',
    lore: 'An offset rack channels the second movement of a broken ancient weapon.',
    artDesign: 'silver offset toothed rack with obsidian ceramic jaws and two opaque crimson second-beat arcs' },
  { id: 'flare-focusing-iris', name: 'Flare Focusing Iris', rarity: 'Rare', price: null, theme: 'infernic', element: null,
    buffs: [{ stat: 'elementalDamage', kind: 'percent', amount: 15 }, { stat: 'health', kind: 'percent', amount: 12 }],
    kitEffects: { damage: [{ actions: ['ultimate'], bonus: .08 }] }, effect: '+15% Elemental Damage ~ +12% Health. Damaging Last Flare deals +8% outgoing damage; normal cost and recovery remain.',
    lore: 'A six-leaf iris holds its scarlet focusing crystal behind a silver siege collar.',
    artDesign: 'silver six-leaf shutter iris with a scarlet faceted focusing crystal and compact siege collar' },
  { id: 'clearwater-manifold', name: 'Clearwater Manifold', rarity: 'Rare', price: null, theme: 'oceanic', element: null,
    buffs: [{ stat: 'health', kind: 'percent', amount: 15 }, { stat: 'defense', kind: 'percent', amount: 12 }],
    kitEffects: { healing: .08, healGauge: 2 }, effect: '+15% Health ~ +12% Defense. Authored healing is 8% stronger. An activation that actually heals grants you 2 Gauge once, not per ally.',
    lore: 'A sapphire-lined manifold returns a measured pulse when a damaged vessel is restored.',
    artDesign: 'silver three-chamber manifold with sapphire ceramic channels and a tiny ivory return piston' },
  { id: 'aegis-return-spring', name: 'Aegis Return Spring', rarity: 'Rare', price: null, theme: 'tranquilitic', element: null,
    buffs: [{ stat: 'defense', kind: 'percent', amount: 15 }, { stat: 'shatterCapacity', kind: 'flat', amount: 15 }],
    kitEffects: { shieldGauge: 2 }, effect: '+15% Defense ~ +15 Shatter Capacity. An activation that actually increases an allied shield grants you 2 Gauge once, not per ally.',
    lore: 'A pearl shield plate compresses a silver return spring only when its ward expands.',
    artDesign: 'silver shield-shaped spring cage with a pearl ward plate and articulated turquoise return levers' },
  { id: 'emberlife-kiln', name: 'Emberlife Kiln', rarity: 'Rare', price: null, theme: 'infernic', element: null,
    buffs: [{ stat: 'elementalDamage', kind: 'percent', amount: 15 }, { stat: 'damage', kind: 'percent', amount: 12 }],
    kitEffects: { burn: .10 }, effect: '+15% Elemental Damage ~ +12% Attack. Authored Burn ticks are 10% stronger; does not add Burn to other skills.',
    lore: 'A compact scarlet kiln measures lasting ember pressure without lengthening its cycle.',
    artDesign: 'silver vaulted kiln with crimson ceramic pressure tiles and two opaque orange ember blades' },
  { id: 'tension-governor', name: 'Tension Governor', rarity: 'Rare', price: null, theme: 'chaotic', element: null,
    buffs: [{ stat: 'defense', kind: 'percent', amount: 15 }, { stat: 'elementalDamage', kind: 'percent', amount: 12 }],
    kitEffects: { weaken: .03 }, effect: '+15% Defense ~ +12% Elemental Damage. Authored Weaken reduces enemy attack by 3 additional percentage points, capped at 60%; duration stays unchanged.',
    lore: 'An obsidian counterweight holds the opposing force of an ancient weakening circuit.',
    artDesign: 'silver twin-jaw governor with an obsidian counterweight and crisp opaque violet tension bars' },
  { id: 'covercharge-drum', name: 'Covercharge Drum', rarity: 'Rare', price: null, theme: 'botanic', element: null,
    buffs: [{ stat: 'health', kind: 'percent', amount: 15 }, { stat: 'defense', kind: 'percent', amount: 12 }],
    kitEffects: { defenseGauge: 3 }, effect: '+15% Health ~ +12% Defense. Legal Defense grants 3 Gauge once, capped by capacity; it still spends your action.',
    lore: 'A stone-and-jade drum catches a reserve pulse as its protective plates close.',
    artDesign: 'silver armored drum with jade ceramic ribs and gray stone protective plates closing around a reserve wheel' },
  { id: 'sootwake-crucible', name: 'Sootwake Crucible', rarity: 'Legendary', price: null, theme: 'infernic', element: null,
    buffs: [{ stat: 'damage', kind: 'percent', amount: 85 }, { stat: 'defense', kind: 'percent', amount: -10 }],
    kitEffects: { damage: [{ actions: ['skill1', 'skill2', 'ultimate'], bonus: .18, condition: 'burning' }] },
    effect: '+85% Attack ~ -10% Defense. Damaging skills deal +18% outgoing damage to targets already Burning before impact; the first application does not qualify.',
    lore: 'A white siege crucible opens layered scarlet baffles around an already-kindled target line.',
    artDesign: 'formidable platinum siege crucible with layered scarlet enamel baffles and an ivory thorn-shaped targeting aperture' },
  { id: 'tidebound-reflector', name: 'Tidebound Reflector', rarity: 'Legendary', price: null, theme: 'oceanic', element: null,
    buffs: [{ stat: 'health', kind: 'percent', amount: 85 }, { stat: 'damage', kind: 'percent', amount: -10 }],
    kitEffects: { damage: [{ actions: ['skill1', 'skill2', 'ultimate'], bonus: .18, condition: 'shielded' }] },
    effect: '+85% Health ~ -10% Attack. Damaging skills deal +18% outgoing damage while you have a positive shield before impact.',
    lore: 'Ivory tide plates redirect a bearer-held ward into a controlled offensive reflection.',
    artDesign: 'majestic platinum shell reflector with ivory tide plates sapphire faceted mirrors and layered opaque blue arcs' },
  { id: 'pressurecrest-governor', name: 'Pressurecrest Governor', rarity: 'Legendary', price: null, theme: 'atmospheric', element: null,
    buffs: [{ stat: 'critMultiplier', kind: 'percent', amount: 85 }, { stat: 'health', kind: 'percent', amount: -10 }],
    kitEffects: { criticalDamage: .12 }, effect: '+85% Critical Damage multiplier ~ -10% Health. Critical direct hits deal 12% more critical damage; noncritical hits and Burn are unchanged.',
    lore: 'A platinum wind governor aligns its open feather vanes around a decisive pressure point.',
    artDesign: 'majestic platinum feather-vane governor with layered teal pressure fins and ivory calibrated crest' },
  { id: 'rootbound-triage-vault', name: 'Rootbound Triage Vault', rarity: 'Legendary', price: null, theme: 'botanic', element: null,
    buffs: [{ stat: 'health', kind: 'percent', amount: 85 }, { stat: 'elementalDamage', kind: 'percent', amount: -10 }],
    kitEffects: { healingBelowHalf: .25 }, effect: '+85% Health ~ -10% Elemental Damage. Authored healing is 25% stronger if your HP is at or below half when that healing activation begins; cannot revive.',
    lore: 'An ivory restoration vault opens its emerald root lattice only under genuine strain.',
    artDesign: 'formidable platinum restoration vault with immense articulated emerald root lattice and ivory sanctuary chambers' },
  { id: 'solace-anchor', name: 'Solace Anchor', rarity: 'Legendary', price: null, theme: 'tranquilitic', element: null,
    buffs: [{ stat: 'defense', kind: 'percent', amount: 85 }, { stat: 'damage', kind: 'percent', amount: -10 }],
    kitEffects: { defenseReduction: .05 }, effect: '+85% Defense ~ -10% Attack. Defense reduces incoming direct damage by 5 additional percentage points; other wards multiply separately.',
    lore: 'An ivory peace anchor locks a folded sanctuary into the bearer’s chosen defensive stance.',
    artDesign: 'majestic platinum sanctuary anchor with ivory folding fortress plates and pearl turquoise peace medallion' },
  { id: 'ruinselect-prism', name: 'Ruinselect Prism', rarity: 'Legendary', price: null, theme: 'chaotic', element: null,
    buffs: [{ stat: 'elementalDamage', kind: 'percent', amount: 85 }, { stat: 'defense', kind: 'percent', amount: -10 }],
    kitEffects: { damage: [{ actions: ['skill1', 'skill2', 'ultimate'], bonus: .18, condition: 'weakened' }] },
    effect: '+85% Elemental Damage ~ -10% Defense. Damaging skills deal +18% outgoing damage to targets already Weakened before impact; the first application does not qualify.',
    lore: 'An obsidian selection prism tracks the fractured pressure of an already-weakened enemy.',
    artDesign: 'formidable platinum selection orrery with fractured obsidian prism and opaque crimson and violet targeting rails' },
  { id: 'infernic-pyre-census', name: 'Pyre Census', rarity: 'Omnic', price: null, theme: 'infernic', element: 'infernic',
    buffs: [{ stat: 'damage', kind: 'percent', amount: 60 }, { stat: 'elementalDamage', kind: 'percent', amount: 50 }, { stat: 'health', kind: 'percent', amount: 40 }],
    kitEffects: { burn: .20, ultimateBurnBonus: .06 }, effect: '+60% Attack ~ +50% Elemental Damage ~ +40% Health. Authored Burn ticks are 20% stronger. Last Flare gains +6% outgoing damage per living Burning enemy at activation start, maximum +18%; normal recovery remains.',
    lore: 'A restored scarlet census engine counts kindled battlefield channels before releasing its crown.',
    artDesign: 'awe-inspiring restored crimson census engine with three immense articulated phoenix crown counters ivory siege ribs and opaque orange thorn rings' },
  { id: 'oceanic-shared-tide-pump', name: 'Shared Tide Pump', rarity: 'Omnic', price: null, theme: 'oceanic', element: 'oceanic',
    buffs: [{ stat: 'health', kind: 'percent', amount: 60 }, { stat: 'defense', kind: 'percent', amount: 50 }, { stat: 'elementalDamage', kind: 'percent', amount: 40 }],
    kitEffects: { shield: .15, shieldRecipientGauge: 3 }, effect: '+60% Health ~ +50% Defense ~ +40% Elemental Damage. Authored skill shields are 15% stronger. Each living ally whose shield actually increases during your activation gains 3 Gauge once; unchanged refreshes do not qualify.',
    lore: 'A fully restored tide pump shares one measured ward pulse across separate protected channels.',
    artDesign: 'awe-inspiring sapphire tide pump with three immense separate pearl shield chambers silver articulated fins and opaque blue shared tide ribbons' },
  { id: 'atmospheric-storm-clock', name: 'Storm Clock', rarity: 'Omnic', price: null, theme: 'atmospheric', element: 'atmospheric',
    buffs: [{ stat: 'damage', kind: 'percent', amount: 60 }, { stat: 'critMultiplier', kind: 'percent', amount: 50 }, { stat: 'defense', kind: 'percent', amount: 40 }],
    kitEffects: { criticalDamage: .10, criticalCooldown: 1 }, effect: '+60% Attack ~ +50% Critical Damage multiplier ~ +40% Defense. Critical direct hits deal 10% more critical damage. A critically hitting ordinary skill shortens its own cooldown by one turn, at most once per round and never ready before next round.',
    lore: 'A completed teal storm clock reindexes a successful strike without changing the combat clock.',
    artDesign: 'awe-inspiring restored teal storm clock with immense articulated turbine feather wheels ivory timing rings and opaque wind and electric zigzag shapes' },
  { id: 'botanic-graft-covenant', name: 'Graft Covenant', rarity: 'Omnic', price: null, theme: 'botanic', element: 'botanic',
    buffs: [{ stat: 'health', kind: 'percent', amount: 60 }, { stat: 'elementalDamage', kind: 'percent', amount: 50 }, { stat: 'defense', kind: 'percent', amount: 40 }],
    kitEffects: { healing: .15, healedSkillCharge: .15 }, effect: '+60% Health ~ +50% Elemental Damage ~ +40% Defense. Authored healing is 15% stronger. Actually healing another ally with an activation primes +15% outgoing damage for your next damaging ordinary skill; one charge, refresh only, consumed before any new healing.',
    lore: 'A restored jade graft engine binds a genuine act of restoration to one measured future strike.',
    artDesign: 'awe-inspiring restored emerald graft engine with immense articulated root arms ivory restoration chambers gray stone braces and opaque jade covenant bands' },
  { id: 'tranquilitic-accord-bastion', name: 'Accord Bastion', rarity: 'Omnic', price: null, theme: 'tranquilitic', element: 'tranquilitic',
    buffs: [{ stat: 'defense', kind: 'percent', amount: 60 }, { stat: 'health', kind: 'percent', amount: 50 }, { stat: 'elementalDamage', kind: 'percent', amount: 40 }],
    kitEffects: { shield: .10, defenseTeamShield: .03 }, effect: '+60% Defense ~ +50% Health ~ +40% Elemental Damage. Authored skill shields are 10% stronger. Defense grants each living ally a shield of 3% of your effective max HP; refreshes to the stronger value, never adds or revives.',
    lore: 'A completed ivory accord mechanism unfolds a small shared sanctuary from a chosen defensive stance.',
    artDesign: 'awe-inspiring restored ivory accord mechanism with immense pearl sanctuary vanes platinum fortress crown and opaque turquoise peace rings' },
  { id: 'chaotic-fault-verdict', name: 'Fault Verdict', rarity: 'Omnic', price: null, theme: 'chaotic', element: 'chaotic',
    buffs: [{ stat: 'elementalDamage', kind: 'percent', amount: 60 }, { stat: 'damage', kind: 'percent', amount: 50 }, { stat: 'health', kind: 'percent', amount: 40 }],
    kitEffects: { weaken: .05, weakenedSkillGauge: 3, ultimatePierce: .15 }, effect: '+60% Elemental Damage ~ +50% Attack ~ +40% Health. Authored Weaken gains 5 percentage points, capped at 60%. A damaging ordinary skill hitting an already Weakened enemy grants 3 Gauge once. Last Flare ignores 15% Defense without changing enemy stats.',
    lore: 'A restored obsidian verdict engine measures an existing fault and opens one precise path through it.',
    artDesign: 'awe-inspiring restored obsidian verdict engine with immense articulated platinum judgment jaws opaque crimson fracture rings and violet prismatic facets' },
] as const satisfies readonly KitConduitDesign[];
