import type { ElementId } from './activities';
import type { ConduitBuff } from './conduits';
import type { ConduitKitEffects } from './conduit-kit';

interface KitConduitDesign {
  id: string;
  name: string;
  rarity: 'Omnic';
  price: null;
  theme: ElementId;
  element: ElementId;
  buffs: readonly ConduitBuff[];
  effect: string;
  lore: string;
  kitEffects: ConduitKitEffects;
  artDesign: string;
}
function stats(first: ConduitBuff['stat'], second: ConduitBuff['stat'], third: ConduitBuff['stat']): ConduitBuff[] {
  return [first, second, third].map((stat, index) => ({ stat, kind: 'percent', amount: [60, 50, 40][index] }));
}

// Every rule has an independent once-per-round gate; generated effects never retrigger authored hooks.
export const kitConduitDesigns = [
  { id: 'tempered-strike-link', name: 'Phoenix Temper Dominion', rarity: 'Omnic', price: null, theme: 'infernic', element: 'infernic',
    buffs: stats('damage', 'defense', 'health'),
    kitEffects: { rule: { trigger: 'direct', actions: ['light'], bank: { trigger: 'burn-tick', maximum: 3 },
      outcomes: [{ kind: 'gauge', recipient: 'self', amount: 2 }] } },
    effect: '+60% Attack, +50% Defense, +40% Health. Actual self-authored Burn damage banks one Temper per round (max 3). An effective Normal Attack spends all Temper for 2 Gauge each, once per round.',
    lore: 'The reborn striking engine tempers its reserve in genuine embers before releasing a measured return.',
    artDesign: 'fully reborn articulated striking-link engine with a readable protected crimson ceramic pivot, six majestic phoenix blade fans, nested orange siege rings, a crown of interlocking impact vanes and densely layered scarlet ribbons' },
  { id: 'mending-valve', name: 'Worldroot Sap Cathedral', rarity: 'Omnic', price: null, theme: 'botanic', element: 'botanic',
    buffs: stats('health', 'elementalDamage', 'defense'),
    kitEffects: { rule: { trigger: 'defense', bank: { trigger: 'heal', maximum: 3 },
      outcomes: [{ kind: 'gauge', recipient: 'injured', amount: 3 }] } },
    effect: '+60% Health, +50% Elemental Damage, +40% Defense. Effective authored healing banks one Sap per round (max 3). Defense spends all Sap to grant the most injured living ally 3 Gauge each, once per round.',
    lore: 'A restored restoration valve stores only the pulse of health actually returned.',
    artDesign: 'fully reborn flower-valve cathedral with a readable protected ivory restoration channel, six majestic jade leaf fans, nested root rings, a petal crown and densely layered emerald covenant ribbons between articulated shutters' },
  { id: 'ward-stitch-spool', name: 'Leviathan Ward Loom', rarity: 'Omnic', price: null, theme: 'oceanic', element: 'oceanic',
    buffs: stats('defense', 'health', 'elementalDamage'),
    kitEffects: { rule: { trigger: 'shield-absorbed', outcomes: [{ kind: 'shield', recipient: 'self', amount: 0, ratio: .25, cap: .03 }] } },
    effect: '+60% Defense, +50% Health, +40% Elemental Damage. Actual direct absorption by your authored shield refreshes your own non-authored shield to 25% of absorbed damage, capped at 3% of your max HP, once per round.',
    lore: 'A completed ward loom recovers the tension spent protecting a living vessel.',
    artDesign: 'fully reborn sapphire ward loom with a readable protected spool between pearl guides, six majestic shell fans, nested tidal rings, a leviathan crest crown and densely layered opaque blue ward ribbons' },
  { id: 'cinder-metering-nozzle', name: 'Eternal Cinder Observatory', rarity: 'Omnic', price: null, theme: 'infernic', element: 'infernic',
    buffs: stats('elementalDamage', 'damage', 'defense'),
    kitEffects: { rule: { trigger: 'direct', actions: ['skill1', 'skill2', 'ultimate'], ownBurn: true,
      bank: { trigger: 'burn-applied', maximum: 1 }, outcomes: [{ kind: 'burn-clock', amount: 1 }] } },
    effect: '+60% Elemental Damage, +50% Attack, +40% Defense. An effective authored Burn application banks one Cinder relay per round (refresh only). A later damaging skill hitting your existing Burn spends it to extend that Burn by one phase, capped at 3 remaining phases, once per round; never adds Burn.',
    lore: 'The restored nozzle holds an ember clock rather than creating a flame from nothing.',
    artDesign: 'fully reborn triangular cinder observatory with a readable protected three-baffle nozzle, six majestic orange flame fans, nested scarlet clock rings, an ember crown and densely layered opaque crimson pressure ribbons' },
  { id: 'pulse-trigger-pawl', name: 'Sky Sovereign Escapement', rarity: 'Omnic', price: null, theme: 'atmospheric', element: 'atmospheric',
    buffs: stats('damage', 'critMultiplier', 'defense'),
    kitEffects: { rule: { trigger: 'defense', bank: { trigger: 'critical', maximum: 1 },
      outcomes: [{ kind: 'cooldown', recipient: 'self', amount: 1 }] } },
    effect: '+60% Attack, +50% Critical Damage multiplier, +40% Defense. An effective critical direct activation banks one Sky tooth per round (refresh only). Defense spends it to shorten your longest available ordinary-skill cooldown by one, never before next round, once per round.',
    lore: 'A sovereign wind escapement returns a successful pressure pulse to a guarded timing wheel.',
    artDesign: 'fully reborn teal ratchet escapement with a readable protected ceramic tooth, six majestic turbine feather fans, nested timing rings, an ivory sky crown and densely layered opaque wind ribbons' },
  { id: 'firstlight-cam', name: 'Firstlight Concordance', rarity: 'Omnic', price: null, theme: 'tranquilitic', element: 'tranquilitic',
    buffs: stats('damage', 'health', 'defense'),
    kitEffects: { rule: { trigger: 'direct', actions: ['light'], bank: { trigger: 'support', maximum: 1, other: true },
      outcomes: [{ kind: 'cooldown', recipient: 'injured-other', amount: 1 }] } },
    effect: '+60% Attack, +50% Health, +40% Defense. Effective authored support to another ally banks one Concordance per round. Your next effective Normal Attack spends it to shorten the most injured other ally’s longest available ordinary-skill cooldown by one, never before next round, once per round.',
    lore: 'A restored opening cam aligns an allied mechanism only after genuine support.',
    artDesign: 'fully reborn ivory concordance cam with a readable protected opening joint, six majestic petal fans, nested precision rings, a pearl sanctuary crown and densely layered turquoise support ribbons between articulated arms' },
  { id: 'secondbeat-rack', name: 'Secondbeat Rupture Throne', rarity: 'Omnic', price: null, theme: 'chaotic', element: 'chaotic',
    buffs: stats('damage', 'elementalDamage', 'defense'),
    kitEffects: { rule: { trigger: 'direct', actions: ['light'], ownWeaken: true,
      bank: { trigger: 'weaken-applied', maximum: 1 }, outcomes: [{ kind: 'fracture', amount: 1 }] } },
    effect: '+60% Attack, +50% Elemental Damage, +40% Defense. An effective authored Weaken application banks one Rupture per round. A later effective Normal Attack on your Weakened target spends it to place one personal Fracture Mark after impact (max 2), once per round.',
    lore: 'The reborn offset rack measures actual suppression before indexing a new fracture.',
    artDesign: 'fully reborn obsidian toothed-rack throne with a readable protected double jaw, six majestic fractured blade fans, nested violet fault rings, a crimson rupture crown and densely layered opaque tension ribbons' },
  { id: 'flare-focusing-iris', name: 'Ember Coronation Iris', rarity: 'Omnic', price: null, theme: 'infernic', element: 'infernic',
    buffs: stats('elementalDamage', 'health', 'damage'),
    kitEffects: { rule: { trigger: 'resource-spent', resources: ['ember'],
      outcomes: [{ kind: 'shield', recipient: 'injured', amount: 0, ratio: .04, cap: .12 }] } },
    effect: '+60% Elemental Damage, +50% Health, +40% Attack. Actually spending intrinsic Infernic Embers refreshes the most injured living ally’s non-authored shield to 4% of your max HP per spent stack (max 12%), once per round; no resource is granted.',
    lore: 'An enthroned iris returns spent native embers as a protective coronation.',
    artDesign: 'fully reborn scarlet six-leaf focusing iris with a readable protected faceted central crystal, six majestic phoenix shield fans, nested coronation rings, an ivory siege crown and densely layered orange protective ribbons' },
  { id: 'clearwater-manifold', name: 'Abyssal Clearwater Parliament', rarity: 'Omnic', price: null, theme: 'oceanic', element: 'oceanic',
    buffs: stats('health', 'defense', 'elementalDamage'),
    kitEffects: { rule: { trigger: 'shield-absorbed', outcomes: [{ kind: 'gauge', recipient: 'lowest-gauge-other', amount: 4 }] } },
    effect: '+60% Health, +50% Defense, +40% Elemental Damage. Actual direct absorption by your authored shield grants the lowest-Gauge other living ally 4 Gauge, once per round; no eligible ally means no effect.',
    lore: 'A restored manifold routes consumed ward pressure to a separate protected chamber.',
    artDesign: 'fully reborn three-chamber sapphire manifold with a readable protected return piston, six majestic pearl tide fans, nested channel rings, an abyssal shell crown and densely layered opaque blue return ribbons' },
  { id: 'aegis-return-spring', name: 'Aegis Covenant Crown', rarity: 'Omnic', price: null, theme: 'tranquilitic', element: 'tranquilitic',
    buffs: stats('defense', 'health', 'elementalDamage'),
    kitEffects: { rule: { trigger: 'defense', bank: { trigger: 'shield-grown', maximum: 1 },
      outcomes: [{ kind: 'boost', recipient: 'injured-other', amount: .08 }] } },
    effect: '+60% Defense, +50% Health, +40% Elemental Damage. An actual authored shield increase banks one Covenant per round. Defense spends it to refresh the most injured other living ally’s outgoing Attack buff to 8% through next round, never stacking or replacing a stronger buff, once per round.',
    lore: 'The restored spring releases protected pressure as a brief ally covenant.',
    artDesign: 'fully reborn pearl shield-spring crown with a readable protected compression cage, six majestic sanctuary plate fans, nested covenant rings, an ivory aegis crown and densely layered turquoise return ribbons' },
  { id: 'emberlife-kiln', name: 'Phoenix Lifeforge', rarity: 'Omnic', price: null, theme: 'infernic', element: 'infernic',
    buffs: stats('health', 'elementalDamage', 'damage'),
    kitEffects: { rule: { trigger: 'burn-tick', outcomes: [{ kind: 'heal', recipient: 'injured-other', amount: 0, ratio: .25, cap: .02 }] } },
    effect: '+60% Health, +50% Elemental Damage, +40% Attack. Actual self-authored Burn HP damage restores the most injured other living ally by 25% of that damage, capped at 2% of your max HP, once per round. This Conduit healing is not authored healing and cannot feed Botanic Renewal.',
    lore: 'The completed kiln salvages a measured ember pulse without pretending it is native restoration.',
    artDesign: 'fully reborn vaulted crimson lifeforge with a readable protected ceramic kiln core, six majestic phoenix petal fans, nested life-channel rings, an ivory furnace crown and densely layered orange restoration ribbons' },
  { id: 'tension-governor', name: 'Fractured Mercy Governor', rarity: 'Omnic', price: null, theme: 'chaotic', element: 'chaotic',
    buffs: stats('defense', 'elementalDamage', 'health'),
    kitEffects: { rule: { trigger: 'direct', ownWeaken: true,
      outcomes: [{ kind: 'shield', recipient: 'injured-other', amount: 0, ratio: .10, cap: .03 }] } },
    effect: '+60% Defense, +50% Elemental Damage, +40% Health. Effective direct HP damage to a target already carrying your authored Weaken refreshes the most injured other living ally’s non-authored shield to 10% of damage, capped at 3% of your max HP, once per round.',
    lore: 'A completed suppression governor diverts a precise fraction of weakened resistance to a separate ward.',
    artDesign: 'fully reborn obsidian twin-jaw governor with a readable protected counterweight, six majestic violet fault fans, nested tension rings, a crimson mercy crown and densely layered opaque fractured ribbons' },
  { id: 'covercharge-drum', name: 'Worldgrove Covercharge Heart', rarity: 'Omnic', price: null, theme: 'botanic', element: 'botanic',
    buffs: stats('defense', 'health', 'elementalDamage'),
    kitEffects: { rule: { trigger: 'heal', other: true, outcomes: [{ kind: 'shield', recipient: 'self', amount: .04 }] } },
    effect: '+60% Defense, +50% Health, +40% Elemental Damage. Actually healing another ally with authored healing refreshes your own non-authored shield to 4% of your max HP, once per round; full-health refreshes do not qualify.',
    lore: 'A restored living drum closes its own plates only when another vessel is truly repaired.',
    artDesign: 'fully reborn jade armored heart drum with a readable protected reserve wheel, six majestic root plate fans, nested grove rings, a gray stone leaf crown and densely layered emerald protective ribbons' },
  { id: 'sootwake-crucible', name: 'Sootwake Phoenix Mirror', rarity: 'Omnic', price: null, theme: 'infernic', element: 'infernic',
    buffs: stats('damage', 'health', 'defense'),
    kitEffects: { rule: { trigger: 'direct', actions: ['light'], ownBurn: true,
      outcomes: [{ kind: 'shield', recipient: 'self', amount: 0, ratio: .10, cap: .04 }] } },
    effect: '+60% Attack, +50% Health, +40% Defense. Effective Normal Attack HP damage to your already Burning target refreshes your own non-authored shield to 10% of damage, capped at 4% of your max HP, once per round; the first Burn application does not qualify.',
    lore: 'The reborn crucible reflects an existing ember channel into a measured self-ward.',
    artDesign: 'fully reborn scarlet siege mirror crucible with a readable protected thorn aperture, six majestic phoenix armor fans, nested sootwake rings, an ivory targeting crown and densely layered orange reflection ribbons' },
  { id: 'tidebound-reflector', name: 'Leviathan Mercy Reflector', rarity: 'Omnic', price: null, theme: 'oceanic', element: 'oceanic',
    buffs: stats('health', 'defense', 'damage'),
    kitEffects: { rule: { trigger: 'shield-grown', outcomes: [{ kind: 'shield', recipient: 'injured', amount: .05 }] } },
    effect: '+60% Health, +50% Defense, +40% Attack. An actual authored shield increase refreshes the most injured living ally’s non-authored shield to at least 5% of your max HP, once per round; stronger shields remain unchanged.',
    lore: 'A completed tide reflector directs a genuine ward expansion toward the vessel under greatest strain.',
    artDesign: 'fully reborn sapphire shell reflector with a readable protected faceted mirror, six majestic ivory tidal plate fans, nested mercy rings, a leviathan pearl crown and densely layered opaque blue shelter ribbons' },
  { id: 'pressurecrest-governor', name: 'Tempest Shelter Sovereign', rarity: 'Omnic', price: null, theme: 'atmospheric', element: 'atmospheric',
    buffs: stats('critMultiplier', 'damage', 'health'),
    kitEffects: { rule: { trigger: 'critical', outcomes: [{ kind: 'shield', recipient: 'injured-other', amount: 0, ratio: .10, cap: .03 }] } },
    effect: '+60% Critical Damage multiplier, +50% Attack, +40% Health. Effective critical direct HP damage refreshes the most injured other living ally’s non-authored shield to 10% of damage, capped at 3% of your max HP, once per round; shield-only hits do not create shelter.',
    lore: 'A restored pressure crest directs real critical impact into an ally shelter rather than another attack.',
    artDesign: 'fully reborn teal feather-vane sovereign with a readable protected pressure governor, six majestic turbine shelter fans, nested calibrated rings, an ivory tempest crown and densely layered opaque wind ribbons' },
  { id: 'rootbound-triage-vault', name: 'Worldroot Triage Sanctuary', rarity: 'Omnic', price: null, theme: 'botanic', element: 'botanic',
    buffs: stats('health', 'defense', 'elementalDamage'),
    kitEffects: { rule: { trigger: 'heal', belowHalf: true, outcomes: [{ kind: 'cooldown', recipient: 'target', amount: 1 }] } },
    effect: '+60% Health, +50% Defense, +40% Elemental Damage. Effective authored healing of an ally at or below half HP before healing shortens that recipient’s longest available ordinary-skill cooldown by one, never before next round, once per round. It neither revives nor bypasses recovery.',
    lore: 'A restored triage vault repairs one timing channel only under genuine pre-heal strain.',
    artDesign: 'fully reborn ivory restoration vault with a readable protected triage chamber, six majestic emerald root fans, nested sanctuary rings, a gray stone petal crown and densely layered jade restoration ribbons' },
  { id: 'solace-anchor', name: 'Solace Witness Monolith', rarity: 'Omnic', price: null, theme: 'tranquilitic', element: 'tranquilitic',
    buffs: stats('defense', 'health', 'damage'),
    kitEffects: { rule: { trigger: 'defense', bank: { trigger: 'support', maximum: 1, other: true },
      outcomes: [{ kind: 'gauge', recipient: 'injured-other', amount: 5 }] } },
    effect: '+60% Defense, +50% Health, +40% Attack. Effective authored healing, shield growth or Attack support to another ally banks one Witness per round (refresh only). Defense spends it to grant the most injured other living ally 5 Gauge, once per round; Defense still spends your action.',
    lore: 'A completed sanctuary anchor stores the witness of a genuine authored covenant before releasing a reserve.',
    artDesign: 'fully reborn ivory sanctuary anchor with a readable protected locking joint, six majestic fortress fans, nested solace rings, a pearl witness crown and densely layered turquoise covenant ribbons' },
  { id: 'ruinselect-prism', name: 'Ruinselect Fracture Parliament', rarity: 'Omnic', price: null, theme: 'chaotic', element: 'chaotic',
    buffs: stats('elementalDamage', 'damage', 'health'),
    kitEffects: { rule: { trigger: 'fracture-spent', outcomes: [{ kind: 'gauge', recipient: 'lowest-gauge-other', amount: 0, ratio: 2 }] } },
    effect: '+60% Elemental Damage, +50% Attack, +40% Health. Actually consuming your personal Fracture Marks with an effective Normal Attack grants the lowest-Gauge other living ally 2 Gauge per consumed Mark (max 4), once per round. It creates no marks and never consumes another owner’s marks.',
    lore: 'The restored selection orrery routes spent personal fractures to one allied reserve.',
    artDesign: 'fully reborn fractured obsidian selection orrery with a readable protected central prism, six majestic violet targeting fans, nested fault rings, a crimson parliamentary crown and densely layered opaque precision ribbons' },
  { id: 'infernic-pyre-census', name: 'Pyre Census Requiem', rarity: 'Omnic', price: null, theme: 'infernic', element: 'infernic',
    buffs: stats('damage', 'elementalDamage', 'health'),
    kitEffects: { rule: { trigger: 'burn-tick', lethal: true, outcomes: [{ kind: 'cooldown', recipient: 'self', amount: 1, bothSkills: true }] } },
    effect: '+60% Attack, +50% Elemental Damage, +40% Health. A self-authored Burn tick that actually defeats its target shortens both of your available ordinary-skill cooldowns by one, never before next round, once per round. Burn retains its source and HP-side damage semantics.',
    lore: 'The completed census records only an ember channel that truly closes.',
    artDesign: 'fully reborn crimson census engine with a readable protected three-counter core, six majestic phoenix requiem fans, nested siege rings, an ivory ember crown and densely layered opaque orange census ribbons' },
  { id: 'oceanic-shared-tide-pump', name: 'Shared Tide Lifesea Engine', rarity: 'Omnic', price: null, theme: 'oceanic', element: 'oceanic',
    buffs: stats('health', 'defense', 'elementalDamage'),
    kitEffects: { rule: { trigger: 'shield-absorbed', other: true,
      outcomes: [{ kind: 'heal', recipient: 'target', amount: 0, ratio: .30, cap: .03 }] } },
    effect: '+60% Health, +50% Defense, +40% Elemental Damage. Actual direct absorption by your authored shield on another living ally restores that recipient by 30% of absorbed damage, capped at 3% of your max HP, once per round. Conduit healing cannot feed native healing resources.',
    lore: 'A completed tide pump repairs the vessel whose authored ward actually bore the pressure.',
    artDesign: 'fully reborn sapphire lifesea pump with a readable protected three-chamber heart, six majestic pearl shield fans, nested tide rings, a silver leviathan crown and densely layered opaque blue restoration ribbons' },
  { id: 'atmospheric-storm-clock', name: 'Tempest Return Chronarch', rarity: 'Omnic', price: null, theme: 'atmospheric', element: 'atmospheric',
    buffs: stats('damage', 'critMultiplier', 'defense'),
    kitEffects: { rule: { trigger: 'resource-spent', resources: ['tempest'], outcomes: [{ kind: 'gauge', recipient: 'self', amount: 0, ratio: 2 }] } },
    effect: '+60% Attack, +50% Critical Damage multiplier, +40% Defense. Actually spending intrinsic Atmospheric Charge returns 2 Gauge per spent stack (max 6), once per round. No resource is granted, action costs and recovery remain, and account upgrades never scale this return.',
    lore: 'A completed storm clock returns a bounded native pressure reserve without moving the combat clock.',
    artDesign: 'fully reborn teal chronarch clock with a readable protected escapement, six majestic turbine feather fans, nested ivory timing rings, a tempest crown and densely layered opaque wind and electric zigzag ribbons' },
  { id: 'botanic-graft-covenant', name: 'Worldroot Graft Coronation', rarity: 'Omnic', price: null, theme: 'botanic', element: 'botanic',
    buffs: stats('health', 'elementalDamage', 'defense'),
    kitEffects: { rule: { trigger: 'resource-spent', resources: ['bloom'],
      outcomes: [{ kind: 'shield', recipient: 'injured', amount: 0, ratio: .03, cap: .09 }] } },
    effect: '+60% Health, +50% Elemental Damage, +40% Defense. Actually spending intrinsic Botanic Renewal refreshes the most injured living ally’s non-authored shield to 3% of your max HP per spent stack (max 9%), once per round; it grants neither healing nor resources.',
    lore: 'The completed graft engine translates a spent native restoration reserve into one protective covenant.',
    artDesign: 'fully reborn emerald graft engine with a readable protected restoration chamber, six majestic articulated root fans, nested covenant rings, an ivory petal crown and densely layered jade protective ribbons across gray stone braces' },
  { id: 'tranquilitic-accord-bastion', name: 'Accord Seraph Sanctuary', rarity: 'Omnic', price: null, theme: 'tranquilitic', element: 'tranquilitic',
    buffs: stats('defense', 'health', 'elementalDamage'),
    kitEffects: { rule: { trigger: 'support', other: true, outcomes: [{ kind: 'protection', recipient: 'target', amount: .10 }] } },
    effect: '+60% Defense, +50% Health, +40% Elemental Damage. Effective authored healing, shield growth or Attack support to another living ally gives that recipient one 10% direct-hit protection charge, refresh only, once per round. It is consumed on their next direct enemy hit, never reduces Burn and resets each encounter.',
    lore: 'A completed accord bastion binds real support to one bounded protective witness.',
    artDesign: 'fully reborn ivory accord bastion with a readable protected sanctuary lock, six majestic seraph fortress fans, nested pearl covenant rings, a turquoise peace crown and densely layered opaque sanctuary ribbons' },
  { id: 'chaotic-fault-verdict', name: 'Rosefault Precision Sovereign', rarity: 'Omnic', price: null, theme: 'chaotic', element: 'chaotic',
    buffs: stats('elementalDamage', 'damage', 'health'),
    kitEffects: { rule: { trigger: 'resource-spent', resources: ['thornAegis', 'duality'],
      outcomes: [{ kind: 'heal', recipient: 'self', amount: 0, ratio: .02, cap: .06 }] } },
    effect: '+60% Elemental Damage, +50% Attack, +40% Health. Actually spending intrinsic Thorn Aegis or Rose Duality restores your own HP by 2% of max HP per spent charge (max 6%), once per round. This is Conduit healing, not authored Rose healing; no resource, Weaken or Burn is granted.',
    lore: 'The completed fault selector distinguishes a genuinely spent Rose reserve from an unearned echo.',
    artDesign: 'fully reborn obsidian rosefault selector with a readable protected forked prism, six majestic crimson thorn fans, nested violet precision rings, a fractured rose crown and densely layered opaque crimson and amethyst fault ribbons' },
] as const satisfies readonly KitConduitDesign[];

export const convertedKitConduitIds: ReadonlySet<string> = new Set(kitConduitDesigns.map((entry) => entry.id));
