// Generated by tools/status_art_revisions.py; regenerate after reviewed exports.
export const statusArtRevisions: Readonly<Record<string, string>> = {
  'abilities/statuses/status-burn.png': '424f90eb0a7ae9e2',
  'abilities/statuses/status-ward.png': 'bc9b4df28bcfe429',
  'abilities/statuses/status-bloom.png': '5460f876814de104',
  'abilities/statuses/status-tempest.png': '8b83fa5526014f29',
  'abilities/statuses/status-focus.png': '66c7374d14a84cc5',
  'abilities/statuses/status-suppression.png': '816384b299d85132',
  'abilities/statuses/status-rose-grace.png': '3760b4080f37223d',
  'abilities/statuses/status-thorn-aegis.png': 'f6780d014cb71c57',
  'abilities/statuses/status-rose-duality.png': 'a067056782118aef',
};
