"""Generate byte-derived cache revisions for universal ability icons."""

import argparse
from hashlib import sha256
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src" / "content" / "ability-art-revisions.ts"
ASSETS = ("universal-defense", "universal-normal-attack")


def revision_source():
    directory = ROOT / "public" / "assets" / "abilities"
    paths = [directory / f"{asset}.png" for asset in ASSETS]
    missing = [str(path) for path in paths if not path.is_file()]
    if missing:
        raise FileNotFoundError(f"Universal ability exports are missing: {missing}")
    lines = ["// Generated by tools/ability_art_revisions.py; regenerate after icon exports.",
             "export const abilityArtRevisions: Readonly<Record<string, string>> = {"]
    for path in paths:
        lines.append(f"  '{path.stem}': '{sha256(path.read_bytes()).hexdigest()[:16]}',")
    return "\n".join([*lines, "};", ""])


def write_revisions():
    OUTPUT.write_text(revision_source(), encoding="utf-8")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    if args.write:
        write_revisions()
        print("Universal ability artwork revisions generated.")
    elif not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != revision_source():
        raise ValueError("Universal ability revisions are stale. Run with --write after reviewed exports.")
    else:
        print("Universal ability artwork revisions match runtime bytes.")
