"""Generate content-versioned character URLs without changing stable asset IDs."""

import argparse
from hashlib import sha256
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src" / "content" / "character-art-revisions.ts"


def revision_source():
    assets = sorted((ROOT / "public" / "assets" / "characters").glob("*.png"))
    if not assets:
        raise FileNotFoundError("Character runtime portraits are missing.")
    lines = ["// Generated by tools/character_art_revisions.py; regenerate after portrait exports.",
             "export const characterArtRevisions: Readonly<Record<string, string>> = {"]
    for asset in assets:
        revision = sha256(asset.read_bytes()).hexdigest()[:16]
        lines.append(f"  '{asset.stem}': '{revision}',")
    return "\n".join([*lines, "};", ""])


def write_revisions():
    OUTPUT.write_text(revision_source(), encoding="utf-8")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    if args.write:
        write_revisions()
        print("Character artwork revisions generated.")
    elif not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != revision_source():
        raise ValueError("Character revisions are stale. Run with --write after reviewed exports.")
    else:
        print("Character artwork revisions match runtime bytes.")
