"""Generate content-versioned URLs for supplied Conduit icons."""

import argparse
from hashlib import sha256
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src" / "content" / "conduit-art-revisions.ts"


def revision_source():
    assets = sorted((ROOT / "public" / "assets" / "conduits").glob("*.png"))
    if len(assets) != 60:
        raise ValueError(f"Expected 60 supplied Conduit icons, found {len(assets)}.")
    lines = ["// Generated by tools/conduit_art_revisions.py; regenerate after Conduit exports.",
             "export const conduitArtRevisions: Readonly<Record<string, string>> = {"]
    for asset in assets:
        revision = sha256(asset.read_bytes()).hexdigest()[:16]
        lines.append(f"  '{asset.stem}': '{revision}',")
    return "\n".join([*lines, "};", ""])


def write_revisions():
    OUTPUT.write_text(revision_source(), encoding="utf-8")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    if args.write:
        write_revisions()
        print("Conduit artwork revisions generated.")
    elif not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != revision_source():
        raise ValueError("Conduit revisions are stale. Run with --write after reviewed exports.")
    else:
        print("Conduit artwork revisions match runtime bytes.")
