"""Install reviewed prism currencies while retaining historical originals/exports."""

import argparse
from hashlib import sha256
from io import BytesIO
import json
from pathlib import Path
import shutil

from PIL import Image
from prepare_art import ROOT, standardize_sprite
from intake_character_refresh import clean
from art_library import art_path

ASSETS = {"Prismatica": "fractalis", "Null-Prismatica": "lycalis"}
SETTINGS = {
    "fractalis": {"keys": [[52, 233, 194]], "radius": 48, "border_only": True,
                  "edge_cleanup": {"source_pixels": 2, "distance_ramp": 60}},
    "lycalis": {"keys": [[84, 235, 204]], "radius": 48, "border_only": True,
                "edge_cleanup": {"source_pixels": 2, "distance_ramp": 60}},
}
MANIFEST = art_path("prism-currency-intake.json", root=ROOT)
REVISIONS = ROOT / "src" / "content" / "currency-art-revisions.ts"


def digest(path):
    return sha256(path.read_bytes()).hexdigest()


def source_path(name):
    return ROOT / "Art" / "source" / "currencies" / f"{name}.png"


def previous_path(asset):
    return ROOT / "Art" / "source" / "currencies" / "previous-runtime" / f"{asset}.png"


def prepare(source, asset, size=256, content=224):
    with Image.open(source) as image:
        return standardize_sprite(clean(image, SETTINGS[asset]), size, content)


def intake(apply=False, remove_incoming=False, review=None):
    if remove_incoming and not apply:
        raise ValueError("Root cleanup requires verified installation.")
    old = json.loads(MANIFEST.read_text(encoding="utf-8")) if MANIFEST.exists() else None
    old_records = {row["asset"]: row for row in old["assets"]} if old else {}
    planned = []
    for name, asset in ASSETS.items():
        incoming = ROOT / f"{name}.png"
        archived = source_path(name)
        source = incoming if incoming.exists() else archived
        runtime = ROOT / "public" / "assets" / "currencies" / f"{asset}.png"
        historical = previous_path(asset)
        image = prepare(source, asset)
        buffer = BytesIO()
        image.save(buffer, format="PNG", optimize=True)
        output = buffer.getvalue()
        previous_hash = old_records[asset]["previous_runtime_sha256"] if old else digest(runtime)
        for path, expected in ((archived, digest(source)), (historical, previous_hash),
                               (runtime, old_records[asset]["runtime_sha256"] if old else previous_hash)):
            if path.exists() and digest(path) != expected:
                raise FileExistsError(f"Conflicting currency artwork: {path}")
        if old and not historical.exists():
            raise FileNotFoundError(historical)
        record = {"asset": asset, "source": str(archived.relative_to(ROOT)),
                  "source_sha256": digest(source), "runtime": str(runtime.relative_to(ROOT)),
                  "runtime_sha256": sha256(output).hexdigest(),
                  "previous_runtime": str(historical.relative_to(ROOT)),
                  "previous_runtime_sha256": previous_hash, "processing": SETTINGS[asset]}
        planned.append((incoming, source, archived, runtime, historical, image, output, record))
    records = {"assets": [row[-1] for row in planned]}
    if old and old != records:
        raise FileExistsError("Currency provenance changed; review before replacement.")
    if review:
        review.parent.mkdir(parents=True, exist_ok=True)
        sheet = Image.new("RGB", (512, 512), "#242429")
        for index, row in enumerate(planned):
            image = row[5]
            sheet.paste(image, (0, index * 256), image)
            pale = Image.new("RGB", (256, 256), "#eee")
            pale.paste(image, (0, 0), image)
            sheet.paste(pale, (256, index * 256))
        sheet.save(review)
        return
    if apply:
        for incoming, source, archived, runtime, historical, _, output, record in planned:
            archived.parent.mkdir(parents=True, exist_ok=True)
            historical.parent.mkdir(parents=True, exist_ok=True)
            if not archived.exists():
                shutil.copyfile(source, archived)
            if not historical.exists():
                shutil.copyfile(runtime, historical)
            runtime.write_bytes(output)
            if digest(archived) != record["source_sha256"] or digest(runtime) != record["runtime_sha256"]:
                raise ValueError(f"Installed currency bytes differ: {asset}")
        MANIFEST.parent.mkdir(parents=True, exist_ok=True)
        MANIFEST.write_text(json.dumps(records, indent=2) + "\n", encoding="utf-8")
        revisions = ["// Generated by tools/intake_prism_currency_art.py.",
                     "export const currencyArtRevisions: Readonly<Record<string, string>> = {"]
        revisions.extend(f"  '{row['asset']}': '{row['runtime_sha256'][:16]}'," for row in records["assets"])
        REVISIONS.write_text("\n".join([*revisions, "};", ""]), encoding="utf-8")
        if remove_incoming:
            for incoming, _, archived, _, _, _, _, _ in planned:
                if incoming.exists():
                    if digest(incoming) != digest(archived):
                        raise ValueError(f"Incoming original changed: {incoming}")
                    incoming.unlink()
    print(f"Both prism currencies {'installed' if apply else 'validated (dry run)'}.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--remove-incoming", action="store_true")
    parser.add_argument("--review", type=Path)
    args = parser.parse_args()
    intake(args.apply, args.remove_incoming, args.review)
