"""Generate byte-derived cache revisions for reviewed status icons."""

import argparse
from hashlib import sha256
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src" / "content" / "status-art-revisions.ts"
ASSETS = ("burn", "ward", "bloom", "tempest", "focus", "suppression",
          "rose-grace", "thorn-aegis", "rose-duality")


def revision_source():
    lines = ["// Generated by tools/status_art_revisions.py; regenerate after reviewed exports.",
             "export const statusArtRevisions: Readonly<Record<string, string>> = {"]
    for asset in ASSETS:
        relative = f"abilities/statuses/status-{asset}.png"
        path = ROOT / "public" / "assets" / relative
        lines.append(f"  '{relative}': '{sha256(path.read_bytes()).hexdigest()[:16]}',")
    return "\n".join([*lines, "};", ""])


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    expected = revision_source()
    if args.write:
        OUTPUT.write_text(expected, encoding="utf-8")
        print("Status artwork revisions generated.")
    elif not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
        raise ValueError("Status artwork revisions are stale; regenerate with --write after reviewed exports.")
    else:
        print("Status artwork revisions match runtime bytes.")
