"""Content-derived shared Story enemy and scenery URL revisions."""
from hashlib import sha256
from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src" / "content" / "story-art-revisions.ts"


def revision_source():
    assets = sorted(path for folder in ("enemies", "backgrounds")
                    for path in (ROOT / "public" / "assets" / folder).glob("story-*.png"))
    if not assets:
        raise FileNotFoundError("Reviewed Story exports are missing.")
    lines = ["// Generated by tools/story_art_revisions.py after reviewed Story exports.",
             "export const storyArtRevisions: Readonly<Record<string, string>> = {"]
    for asset in assets:
        key = f"{asset.parent.name}/{asset.name}"
        lines.append(f"  '{key}': '{sha256(asset.read_bytes()).hexdigest()[:16]}',")
    return "\n".join([*lines, "};", ""])


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    content = revision_source()
    if args.write:
        OUTPUT.write_text(content, encoding="utf-8")
    elif not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
        raise ValueError("Story revisions are stale; rerun with --write after reviewed exports.")
    print("Story revisions match exported bytes.")
